/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FileRouteImport } from './routes/file'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as MayaRouteImport } from './routes/maya'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as ProcessMapRouteImport } from './routes/process-map'
import { Route as TrackRouteImport } from './routes/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FileRoute = FileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaRoute = MayaRouteImport.update({
  id: '/maya',
  path: '/maya',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessMapRoute = ProcessMapRouteImport.update({
  id: '/process-map',
  path: '/process-map',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/file': typeof FileRoute
  '/guide': typeof GuideRoute
  '/guidelines': typeof GuidelinesRoute
  '/maya': typeof MayaRoute
  '/prepare': typeof PrepareRoute
  '/process-map': typeof ProcessMapRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/file': typeof FileRoute
  '/guide': typeof GuideRoute
  '/guidelines': typeof GuidelinesRoute
  '/maya': typeof MayaRoute
  '/prepare': typeof PrepareRoute
  '/process-map': typeof ProcessMapRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/file': typeof FileRoute
  '/guide': typeof GuideRoute
  '/guidelines': typeof GuidelinesRoute
  '/maya': typeof MayaRoute
  '/prepare': typeof PrepareRoute
  '/process-map': typeof ProcessMapRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/file'
    | '/guide'
    | '/guidelines'
    | '/maya'
    | '/prepare'
    | '/process-map'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/file'
    | '/guide'
    | '/guidelines'
    | '/maya'
    | '/prepare'
    | '/process-map'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/file'
    | '/guide'
    | '/guidelines'
    | '/maya'
    | '/prepare'
    | '/process-map'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FileRoute: typeof FileRoute
  GuideRoute: typeof GuideRoute
  GuidelinesRoute: typeof GuidelinesRoute
  MayaRoute: typeof MayaRoute
  PrepareRoute: typeof PrepareRoute
  ProcessMapRoute: typeof ProcessMapRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file': {
      id: '/file'
      path: '/file'
      fullPath: '/file'
      preLoaderRoute: typeof FileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya': {
      id: '/maya'
      path: '/maya'
      fullPath: '/maya'
      preLoaderRoute: typeof MayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-map': {
      id: '/process-map'
      path: '/process-map'
      fullPath: '/process-map'
      preLoaderRoute: typeof ProcessMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FileRoute: FileRoute,
  GuideRoute: GuideRoute,
  GuidelinesRoute: GuidelinesRoute,
  MayaRoute: MayaRoute,
  PrepareRoute: PrepareRoute,
  ProcessMapRoute: ProcessMapRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
